### ISSUE TITLE
Check-in

### ISSUE THREAD

**Issue by peterdsharpe** [KikeM/winglets#1]
Hey!

Was just curious how this project ended up working out and if you had any feedback on any unintuitive syntax, missing features, etc.!

-Peter

**Comment by emvalbuena** [comment]
Hi @peterdsharpe!

Thanks for checking in man ;) So, it was going well until I ran into a small bug within [my parametrization of the winglet](https://github.com/KikeM/winglets).

And so then I got distracted with [another project](https://github.com/KikeM/degiro-wrapper) that also urges me. 

Nevertheless, I was thinking I had to retake this soon, and your check-in has definitely been a good trigger ;) I'll push it forward so you can add it as a show case to your repo (and give you feedback, I have some cool ideas for your repo I would like to implement via a PR)!

How are you doing by the way? Both work and health.

**Comment by emvalbuena** [comment]
Hi Peter!

How are you doing?

I finished this work, check it out and thank you for your library once again ;)
